---
title: "Methods and Results"
format: html
---

Below is a detailed description of the methods used to generate the index of groundwater availability and the associated results. These are copied from the associated publication. 

## Methods

Field observations suggested that the location of groundwater discharge to streams (i.e., springs) could be predicted based on geology and topography alone (Pourtaghi and Pourghasemi 2014, Leach et al. 2017). We therefore used MaxEnt version 3.4.4 (Phillips and Dudík 2008, Elith et al. 2011; <https://biodiversityinformatics.amnh.org/open_source/maxent/>, accessed on 17 July 2023), a presence-only machine learning technique, to predict the prevalence of springs throughout the USRW (Gerlach et al. 2022). Between 2019 and 2023, we opportunistically collected 105 GPS locations of springs. We identified springs as either (1) areas where water actively upwelled from surface substratum within riparian and floodplain areas or (2) locations where water flowed laterally out of a hillside, typically at valley-bottom toeslopes (floodplain and upland hillslope springs, respectively, sensu Stevens et al. 2021). We combined field observations with 77 additional locations downloaded from the Groundwater Atlas of Wyoming (<https://portal.wsgs.wyo.gov/arcgis/apps/webappviewer/index.html?id=181c32a872a346bfae3579a62230a65a>, accessed on 15 July 2023), filtered to remove hot springs as geothermal activity likely exerts different controls on stream ecosystems than “cold” groundwater inputs that were the focus of this study. Spring locations downloaded from the Groundwater Atlas of Wyoming were previously digitized from U.S. Geological Survey 1:100,000 scale topographic maps covering the state of Wyoming. 

Following Gerlach et al. (2022), we modeled the prevalence of groundwater springs across the USRW using the 182 spring locations as presence points and 11 geologic and topographic layers as predictors. Geologic layers included bedrock and surficial geology (Love and Christiansen 1985), which are known to control both deep and shallow groundwater storage capacity (Tague et al. 2007, O’Sullivan et al. 2020, Dralle et al. 2023), and distance to geologic lineaments (i.e., bedrock fractures), which are known to affect groundwater flow paths (Mallast et al. 2011). Underlying geology interacts with topographic features to determine locations of groundwater discharge to streams. We used the DEM to extract elevation, slope, profile curvature, profile curvature range, planform curvature, planform curvature range, and terrain ruggedness index for the USRW (Gerlach et al. 2022). Steep slopes may represent steep hydraulic gradients driving shallow groundwater flow (Haitjema and Mitchell-Bruker 2005). Profile curvature measures surface curvature parallel to the slope, while planform curvature measures surface curvature perpendicular to the slope. We calculated the range of profile and planform curvature and terrain ruggedness index within a 3 x 3 cell (ca. 30 x 30 m) window to measure variation in curvature over short distances and topographic heterogeneity, respectively. Curvature, curvature range, and terrain ruggedness index may indicate slope failures induced by groundwater discharge (Reid and Iverson 1992), stream headwaters formed by groundwater discharge (Jaeger et al. 2007), and abrupt changes in slope where the water table may be close to the ground surface (Winter 2001, Detty and McGuire 2010). We used the curvature and tri functions in the R package spatialEco (Evans and Murphy 2023) to calculate curvature and terrain ruggedness and the focal function in the R package terra (Hijmans 2023) to calculate curvature range. Finally, we calculated distance to flowlines using the gDistance function in the R package rgeos (Bivand and Rundel 2023). Flowlines represent areas where the water table is near or above the ground surface (Winter 1999) and the upstream extent of flowlines is associated with stream headwaters formed by groundwater discharge (Jaeger et al. 2007). Geologic layers and the DEM used to prepare topographic layers were accessed from the Wyoming Geospatial Hub on 17 July 2023 (<https://data.geospatialhub.org/>). 

We modeled the prevalence of groundwater springs using a logistic model with the default parameters, except for a default prevalence value of 0.1, as we expected springs to be uncommon at the landscape scale. Of the 182 spring locations, 70% (n = 128) were used for model training and 30% (n = 54) were used for model testing. We did not test for or exclude predictor variables that were correlated as our primary goal was to build a model with high predictive accuracy, rather than to make inference on the effect of any single variable. We assessed model performance by calculating the area under the receiver operating curve (AUC): the probability that a randomly chosen presence point will be ranked above a randomly chosen background location (Phillips and Dudík 2008). 

While accounting for spatial bias in search effort can help increase the accuracy of MaxEnt modeling (Kramer-Schadt et al. 2013), we did not consider this necessary for three reasons. First, fieldwork over five years brought us to most areas within the USRW and we therefore did not think search effort was systematically biased towards certain locations. Second, combining field observations with the Groundwater Atlas of Wyoming increased our sample size of spring locations in high elevation, headwater areas that were difficult to access on foot. Third, the model output describing spring prevalence aligned well with our a priori understanding of groundwater activity in the region (refer to Study System and Species). Therefore, we considered the spatial clustering of spring locations to be a real pattern (sensu Winter 2001), rather than an artifact of unequal search effort. 

From the MaxEnt model output (a raster of spring prevalence, where the value for each ca. 10 x 10 m cell represents the probability of the cell containing a groundwater spring), we derived a metric describing groundwater influence on stream conditions. We buffered (100 m radius) the prevalence raster to the stream network as we assumed only groundwater discharging from springs adjacent to flowlines exert influence on stream conditions, such as temperature. We then used WhiteboxTools to delineate catchments for 13,083 locations spaced every 300 m (the distance between study reaches) across the stream network (hereafter, network locations), 32 stream temperature monitoring locations, and 52 study reaches (the downstream extent of four reaches within each of the 13 focal streams). Deriving a metric of groundwater influence across the entire stream network was necessary to allow for projections of growth and production at this scale. We restricted network locations to those with catchments <500 km2 as we assumed groundwater effects on ecosystem processes likely differ between large rivers and smaller tributary streams that were the focus of our study. For each watershed corresponding to either a network, temperature, or study location, we calculated a distance-weighted mean prevalence from the buffered spring prevalence raster. Our weighting scheme used inverse exponential weights with an e-folding distance (the distance at which the weight is 1/e) of 5 km (Isaak et al. 2010). This approach assumes that springs located immediately upstream of a given point exert the greatest influence on local stream conditions, while springs located further upstream are exponentially less likely to affect conditions at the location of interest. To aid interpretation, we normalized the metric of groundwater influence to 0-1 based on the minimum and maximum values calculated for the 13,083 network locations. We used the normalized, distance-weighted mean spring prevalence within the contributing catchment to describe relative groundwater influence at each network, temperature, or study location (hereafter, groundwater index or GWI).


## Results

The MaxEnt model describing groundwater spring prevalence performed well: model area under the curve (AUC) values were 0.93 for both training and testing data. In order of importance, spring prevalence was a function of distance to flowlines, bedrock geology, profile curvature range, surficial geology, elevation, and distance to geologic lineaments, with all other variables contributing little to no information (Table 1). Collectively, the model indicated that ***groundwater springs occurred near flowlines where topography changes abruptly over small distances in valley-bottom areas underlain by coarse glacial deposits*** (i.e., toe slopes formed by stream channel incision into unconsolidated alluvium and colluvium). While springs were predicted to be widespread throughout the upper Snake River watershed, they were most heavily concentrated in the southwestern, eastern, and northern portions of the study area, driving similar spatial patterns in derived GWI. Network locations with high GWI were rare at the scale of the upper Snake River watershed: locations with GWI >0.5 represented just 2.8% of all locations for which the index was derived.


## References

* Bivand, R., and C. Rundel. 2023. rgeos: Interface to Geometry Engine - Open Source ('GEOS'). R package version 0.6-3, https://CRAN.R-project.org/package=rgeos.
* Detty, J. M., and K. J. McGuire. 2010. Topographic controls on shallow groundwater dynamics: Implications of hydrologic connectivity between hillslopes and riparian zones in a till mantled catchment. Hydrological Processes 24:2222–2236.
* Dralle, D. N., G. Rossi, P. Georgakakos, W. J. Hahm, D. M. Rempe, M. Blanchard, M. E. Power, W. E. Dietrich, and S. M. Carlson. 2023. The salmonid and the subsurface: Hillslope storage capacity determines the quality and distribution of fish habitat. Ecosphere 14:1–23.
* Elith, J., S. J. Phillips, T. Hastie, M. Dudík, Y. E. Chee, and C. J. Yates. 2011. A statistical explanation of MaxEnt for ecologists. Diversity and Distributions 17:43–57.
* Evans, J. S., and M. A. Murphy. 2023. spatialEco. R package version 2.0-1, https://github.com/jeffreyevans/spatialEco.
* Gerlach, M. E., K. C. Rains, E. J. Guerrón-Orejuela, W. J. Kleindl, J. Downs, S. M. Landry, and M. C. Rains. 2022. Using remote sensing and machine learning to locate groundwater discharge to salmon-bearing streams. Remote Sensing 14.
* Haitjema, H. M., and S. Mitchell-Bruker. 2005. Are water tables a subdued replica of the topography? Ground Water 43:781–786.
* Hijmans, R. 2023. terra: Spatial Data Analysis. R package version 1.7-39, https://CRAN.R-project.org/package=terra.
* Isaak, D. J., C. H. Luce, B. E. Rieman, D. E. Nagel, E. E. Peterson, D. L. Horan, S. Parkes, and G. L. Chandler. 2010. Effects of climate change and wildfire on stream temperatures and salmonid thermal habitat in a mountain river network. Ecological Applications 20:1350–1371.
* Jaeger, K. L., D. R. Montgomery, and S. M. Bolton. 2007. Channel and perennial flow initiation in headwater streams: Management implications of variability in source-area size. Environmental Management 40:775–786.
* Kramer-Schadt, S., J. Niedballa, J. D. Pilgrim, B. Schröder, J. Lindenborn, V. Reinfelder, M. Stillfried, I. Heckmann, A. K. Scharf, D. M. Augeri, S. M. Cheyne, A. J. Hearn, J. Ross, D. W. Macdonald, J. Mathai, J. Eaton, A. J. Marshall, G. Semiadi, R. Rustam, H. Bernard, R. Alfred, H. Samejima, J. W. Duckworth, C. Breitenmoser-Wuersten, J. L. Belant, H. Hofer, and A. Wilting. 2013. The importance of correcting for sampling bias in MaxEnt species distribution models. Diversity and Distributions 19:1366–1379.
* Leach, J. A., W. Lidberg, L. Kuglerova, A. Peralta-Tapia, A. Agren, and H. Laudon. 2017. Evaluating topography-based predictions of shallow lateral groundwater discharge zones for a boreal lake-stream system. Water Resources Research 53:5420–5437.
* Love, J. D., and A. C. Christiansen. 1985. Geologic map of Wyoming: U.S. Geological Survey Geologic Map, scale 1:500,000, 3 sheets.
* Mallast, U., R. Gloaguen, S. Geyer, T. Rüdiger, and C. Siebert. 2011. Derivation of groundwater flow-paths based on semi-automatic extraction of lineaments from remote sensing data. Hydrology and Earth System Sciences 15:2665–2678.
* O’Sullivan, A. M., K. J. Devito, J. Ogilvie, T. Linnansaari, T. Pronk, S. Allard, and R. A. Curry. 2020. Effects of Topographic Resolution and Geologic Setting on Spatial Statistical River Temperature Models. Water Resources Research 56:1–23.
* Phillips, S. J., and M. Dudík. 2008. Modeling of species distributions with Maxent: new extensions and a comprehensive evaluation. Ecography 31:161–175.
* Pourtaghi, Z. S., and H. R. Pourghasemi. 2014. GIS-based groundwater spring potential assessment and mapping in the Birjand Township, southern Khorasan Province, Iran. Hydrogeology Journal 22:643–662.
* Reid, M. E., and R. M. Iverson. 1992. Gravity‐driven groundwater flow and slope failure potential: 2. Effects of slope morphology, material properties, and hydraulic heterogeneity. Water Resources Research 28:939–950.
* Stevens, L. E., E. R. Schenk, and A. E. Springer. 2021. Springs ecosystem classification. Ecological Applications 31.
* Tague, C., M. Farrell, G. Grant, S. Lewis, and S. Rey. 2007. Hydrogeologic controls on summer stream temperatures in the McKenzie River basin, Oregon. Hydrological Processes 21:3288–3300.
* Winter, T. C. 1999. Relation of streams, lakes, and wetlands to groundwater flow systems. Hydrogeology Journal 7:28–45.
* Winter, T. C. 2001. The concept of hydrologic landscapes. Journal of the American Water Resources Association 37:335–349.
